### ISSUE TITLE
any guide to get a quick start ?

### ISSUE THREAD

**Issue by SeekPoint** [akanimax/natural-language-summary-generation-from-structured-data#3]
plug_and_play.pickle

**Comment by SeekPoint** [comment]
where is the plug_and_play.pickle

**Comment by akanimax** [comment]
I am working on the readme.

**Comment by akanimax** [comment]
To generate the plug_and_play.pickle, you need to run the fast_preprocessing_part1 and part2 scripts.
Also, download the wiko-biography dataset and put the train.nb, train.sent and train.box files in the data folder.

**Comment by SeekPoint** [comment]
waitting the detail readme. thanks

**Comment by akanimax** [comment]
Hi @loveJasmine, I have been busy with my GAN projects lately. Will work on the documentation here soon. 

Cheers!

**Comment by akanimax** [comment]
I have created an initial README.md. let me know if any specific details are to be added.

Cheers :beers:!
@akanimax

**Comment by SeekPoint** [comment]
I had pass fast_prep_1,2
however, it looks missing some file when trainging:

mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$ python3 trainer_with_copy_net.py
Traceback (most recent call last):
  File "trainer_with_copy_net.py", line 4, in <module>
    from Summary_Generator.Model import *
  File "/home/mldl/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation/Summary_Generator/Model.py", line 16, in <module>
    from seq2seq.metrics.bleu import moses_multi_bleu
ImportError: No module named 'seq2seq.metrics'
mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$ ll
total 1704668
drwxrwxr-x 4 mldl mldl       4096 9月  21 23:33 ./
drwxrwxr-x 7 mldl mldl       4096 9月  21 23:55 ../
-rw-rw-r-- 1 mldl mldl      16179 9月  21 17:14 Data_Preprocessor.ipynb
-rw-rw-r-- 1 mldl mldl       7035 9月  21 17:14 Data_Preprocessor.py
-rw-rw-r-- 1 mldl mldl       3830 9月  21 17:34 fast_data_preprocessor_part1.py
-rw-rw-r-- 1 mldl mldl       3001 9月  21 17:14 fast_data_preprocessor_part2.py
-rw-rw-r-- 1 mldl mldl         74 9月  21 17:14 .gitignore
-rw-rw-r-- 1 mldl mldl      61340 9月  21 17:14 Graph_Builder.ipynb
-rw-rw-r-- 1 mldl mldl       1995 9月  21 17:14 inferencer.py
drwxrwxr-x 2 mldl mldl       4096 9月  21 17:14 seq2seq/
drwxrwxr-x 5 mldl mldl       4096 9月  21 17:19 Summary_Generator/
-rw-rw-r-- 1 mldl mldl 1745437383 9月  21 23:36 temp.pickle
-rw-rw-r-- 1 mldl mldl       4100 9月  21 17:14 trainer_with_copy_net.py
-rw-rw-r-- 1 mldl mldl       4360 9月  21 17:14 trainer_without_copy_net.py
mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$ ll seq2seq/
total 8
drwxrwxr-x 2 mldl mldl 4096 9月  21 17:14 ./
drwxrwxr-x 4 mldl mldl 4096 9月  21 23:33 ../
mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$

**Comment by akanimax** [comment]
@loveJasmine, Oh yes! The seq-2-seq is just a link to the repo. Will fix it soon. Thanks for pointing. 
Just a quick fix for you -> clone this repo [seq2seq](https://github.com/google/seq2seq) locally in this project and run the `setup.py` as follows:
    
    (your_venv)$ python setup.py install

And, then run the training script. Thanks.

Best regards,
@akanimax

**Comment by SeekPoint** [comment]
on py3+tf1.0.0

(.venv) mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$ 
(.venv) mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$ PYTHONPATH=seq2seq python3 trainer_with_copy_net.py
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Unpickling the data from the disc ...
Traceback (most recent call last):
  File "trainer_with_copy_net.py", line 83, in <module>
    X, Y = synch_random_shuffle_non_np(zip(field_encodings, content_encodings), label_encodings)
  File "/home/mldl/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation/Summary_Generator/Tensorflow_Graph/utils.py", line 63, in synch_random_shuffle_non_np
    X[:], Y[:] = zip(*combined)
TypeError: 'zip' object does not support item assignment
(.venv) mldl@ub1604:~/ub16_prj/natural-language-summary-generation-from-structured-data/TensorFlow_implementation$

**Comment by akanimax** [comment]
@loveJasmine, 
Fixed in [4a164c81d88dba1eaf9c1a3737e127127ff6471a](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/commit/4a164c81d88dba1eaf9c1a3737e127127ff6471a). Thanks!

Best regards,
@akanimax

**Comment by akanimax** [comment]
Closing this issue now

Thanks
:+1:
