### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by ArijeetC** [akanimax/natural-language-summary-generation-from-structured-data#5]
Whenever I run the fast_data_preprocessor_part1.py file to generate the plug_and_play_pickle file, it gets killed. What is the minimum memory requirement to run this project?

**Comment by akanimax** [comment]
@ArijeetC alright. This is a very compute heavy network architecture. The configuration that we ran this project on, is: 
i) Intel Xeon E5-2697 
ii) 32GB RAM
iii) Nvidia P5000 and P100 GPUs

I'll suggest you lease an AWS gpu instance or use the GCP machine to run this.

**Comment by ArijeetC** [comment]
Do you have any readymade version of the plug_and_play_pickle that I can directly use without preprocessing?

**Comment by akanimax** [comment]
Hi @ArijeetC, I'll see if I still have the processed plug_and_play file.
