### ISSUE TITLE
prepare_tokenizer(field_words) TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by jayurbain** [akanimax/natural-language-summary-generation-from-structured-data#8]
![image](https://user-images.githubusercontent.com/3729362/48721851-51ac8180-ebe8-11e8-9537-6bb725ea066f.png)

Guidance would be appreciated.
Thanks,
Jay

**Comment by akanimax** [comment]
Please read the documentation for the prepare_tokenizer [here](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/blob/master/TensorFlow_implementation/Summary_Generator/Text_Preprocessing_Helpers/utils.py#L94). Note that the argument `words` is actually a `list[list[str]]`. In your case it seems, you are passing a flat list to the function.
Hope this helps.

Best regards,
@akanimax

**Comment by akanimax** [comment]
Closing this issue now. Please let me know in the post closure comments if you still need help.
