### ISSUE TITLE
where is python trainer_with_copy_net.py and python trainer_without_copy_net.py

### ISSUE THREAD

**Issue by SeekPoint** [akanimax/natural-language-summary-generation-from-structured-data#9]

**Comment by akanimax** [comment]
These two files are located inside the base implementation directory titled [`tensorflow_implementation`](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/tree/master/TensorFlow_implementation). Hope this helps.

Best regards,
@akanimax 

p.s. Closing the issue
